apiVersion: v1
kind: Service
metadata:
  name: patientappapp-service
  namespace:   
spec:
  selector:
    app: patientappapp
  ports:
    - port: 85      
      targetPort: 8090
  type: LoadBalancer
